name: ci

on: [push, pull_request]

jobs:
  CI:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.12.0

      - name: Install deps
        run: |
          opam install core

      - name: Run
        run: |
          opam exec -- dune exec ./AoC_2021.exe
